config/routes.rb
RestoreTheChiefApp::Application.routes.draw do
  resources :site_setups


  resources :posts


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
 
  
 # match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
  devise_scope :user do
      root :to => "home#index" #root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
 devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  resources :users do
    get 'invite', :on => :member
  end
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @message = Message.new
    @recent_post = Post.where(:published => true, :display_date => Date.today-500.year..Date.today).first(3)
  end
end

app/helpers/home_helper.rb
module HomeHelper
  
   
end

app/views/home/_recent_posts.html.erb
	   <% if @site_setup.blog_active? %>
	  
	   <% if @recent_post.count == 3 %> 
	<!-- Start of Recent Post --> 
	
	
	<div class="content">
	<div class="featured">
						 <div class="title">
							 <h4>Recent Posts</h4>
						 </div>
						 
						 </div> 
						 
	
	 		 
			<% @recent_post.each.with_index do |recent_posts, index| %>

			 <!-- Start of loop -->
			 <% if index == 0 %> 
	 
			 <!-- index 1 -->
		     <div class="box three first">
			<% end%>
	
			 <% if index == 1 %> 
			 <!-- index 2 -->
		     <div class="box three">
			<% end%>


			 <% if index == 2 %> 
			 <!-- index 3 -->
		     <div class="box three last">
			<% end%>
	
		   		<div class="widget">
						 <div class="featured">  
							 <div class="recent_posts classic">
								 <ul> <li class="date">
										 <span class="day"><%= recent_posts.display_date.strftime("%d") %> </span>
								 
										 <%= recent_posts.display_date.strftime("%b") %>  
									    </li>
										 <li>
											 <span class="title"> <%= link_to recent_posts.title , post_path(recent_posts)  %> </span>
									 
											 <%=h truncate(recent_posts.body, :length => 120) %> </li></ul> 

			 				</div>	 
		 			   </div>	 
			 	  </div>	 
	 
			 </div>	
		<!-- End of loop -->
			<% end%>
				
    
  
			 
     </div>   
	 
	<!-- end of  recent post --> 
	 
   <% end %>
      <% end %>

app/views/home/index.html.erb
	
          <% if @site_setup.kickstarter? %> 
	<div class="ribbon-wrapper-green "><div class="ribbon-green"> <%= link_to 'View on KickStarter', "https://www.kickstarter.com/projects/2127375929/restore-the-chief-rescuing-a-piece-our-our-heritag" %></div></div>
 <% end %>
 
 
<div class="main_sheets">
	<a href="#" class="scrollup"></a>
<div class="containers">

 <div class="branding">
Restore the Chief  
	</div>
      <div class="topbox">
  
      <%= image_tag("side_main_airplane.jpg", :class=>"image-size-std push_down" )%>
     
        <h2 class="hook content">  
          <span class="highlight">1946 Aeronca Chief 11BC-1343</span> 
                  <br>
        <span class="sub-title white">
          Rescuing A Piece our Heritage
        </span></h2>
 
      </div>




 
<br>
<br>
      <div id="project" class="main-content-container"   style=" padding-top: 15px; margin-top: -15px;">

        <div class="subheading">
          <h2 class="hook content">
                 
                   
                   
                          
            <span class="highlight">The Project: </span>
                        <br>
                         The Restoration of 1343 - a Vintage 1946 Aeronca Chief 11BC <br>  
						  <br>  
						 
						 <%= image_tag("Front_airplane.jpg", :class=>"image-size-std" )%>
          </h2>
		  
		  
     <%= render :partial => 'recent_posts' %>
	 
 
		  
          <div id="passion"  class="content "  style=" padding-top: 15px; margin-top: -15px;">
            <h2>
              The Passion
            </h2>
  		<p>With each passing day, the advancements in technology never cease to amaze me. We have come so far as a society,  but while we are still discovering the secrets of the universe, pieces of our heritage lay rotting and dying in barns across our countries.</p><p> <strong>I have been given the rare and unique opportunity to preserve a piece of aviation history.  </strong> This is a gift that I want to share with you.  With your partnership, we can together save, restore, and preserve an aircraft relic for the educational advancement and enjoyment for future generations.  My passion is to preserve this piece of history and not let it be left as just a picture in a history book.   
			</p><p>The 11BC-1343 was built in 1946,  unlike many of it's relatives - it has survived the test of time, but currently lays in pieces.  1343 has seen many good times and could tell many stories. With your help, 1343 could see many more.  I have the skills, ability and time to complete this rescue mission, but 1343 and I  need your support. I can assure you that every penny from this Kickstarter will be going to towards the restoration of the aircraft.  Your support will be used for such things as parts, certifications and tools as well as any unforeseen issues that may arise along the way.
				</p><p>
			     As time goes on, these gems will be found less and less and be found in worst condition.

			Our children may never know what these beauties looked like, or sounded like. They may never know the feeling you get while flying in these vintage aircraft, which were made during a simpler time and know what is it like to be a part of the sky in a pipe box cover in fabric. </p><p>  Please join me in this rescue mission - We need to  <strong>Restore the Chief</strong>
   </p> 
        </div>
		  
          <div class="darker">
            <div class="pullquote content">
              
                           
                           
				<span class="quote open">“</span>The desire to fly is an idea handed down to us by our ancestors who, in their grueling travels across trackless lands in prehistoric times, looked enviously on the birds soaring freely through space, at full speed, above all obstacles, on the infinite highway of the air.<span class="quote">”</span>
			 <div class="pullquote-source">&mdash;Orville Wright</div>
                           
            
            </div>
          </div>
		  
		  
        </div>
		
		</div>
		
	 
		
        <div id="plane"  class="content"  style="padding-top: 15px; margin-top: -15px;">
          <h2>
            1343 - The Airplane
          </h2>
		  
			 <%= image_tag("Front_fuse.jpg", :class=>"image-size-std  rocket-icon" )%>
</h2>
          <h3>
            1343, built in 1946
          </h3>
		  <p>built in 1946 in Vandalia, Ohio by the Aeronca Aircraft Corporation. 1343 was built as a 11AC model but in 1981 it was converted to a 11BC model and used as a float plane. 1343 saw many lakes and streams. As is common with the materials used in those days, the fabric has deteriorated and the frame must be rebuilt. </p>
          <ul>
            <li>
              A Single Engine, two seater plane
            </li>
            <li>
              Has a Continental C85 Engine with 400 hours
            </li>
            <li>
              Was ordinary configured as a float plane
            </li>
	  
            <li>
              Restoration started by an expert many years ago
			  
            </li>
			
            <li>
              Is located in the back of a shed
            </li>
			
            <li>
              Everything in boxes
            </li>
			
			
            <li>
              Wooden Spars need Replacing
            </li>
			
			
            <li>
              Wing Bows Need Replacing
            </li>
            <li>
              	The fuselage is intact but is in need of a fair amount of work.
            </li>
	 
			
			
			
          </ul>
          <h4>
            <em>Currently in disrepair beyond recognition.</em> &mdash; 1343 is a perfect candidate for restoration
          </h4>
          
                
				   <%= image_tag("rafters_fuse.jpg", :class=>"image-size-std  rocket-icon" )%>
        </div>

        <div class="darker">
          <div class="benefits content">

            <div class="clear">
              <h2>
                Pieces of the puzzle
              </h2>
            </div>


            <div class="benefit">
               <%= image_tag("rafters_fuse.jpg", :class=>"image-size-icon icon" )%>
              <h4>
               Fuselage
              </h4>
            </div>
            <div class="benefit">
              <%= image_tag("prop.jpg", :class=>"image-size-icon icon" )%>
              <h4>
               Propeller
              </h4>
            </div>
            <div class="benefit">
               <%= image_tag("engine.jpg", :class=>"image-size-icon icon" )%>
              <h4>
                Continental C85 Engine
              </h4>
            </div>
            <div class="benefit">
               <%= image_tag("wing.jpg", :class=>"image-size-icon icon" )%>
              <h4>
                The Wing<br>(Disassembled)
              </h4>
            </div>

            <div  class="clear sub-description"  >

            </div>
          </div>
        </div>

        
        <div id="challenge"  class="contents"  style=" padding-top: 15px; margin-top: -15px;">
          <h2>
            The Challenge
          </h2>
		<p>


			The plane has been disassembled and is in pieces. This presents the biggest challenge.
			The wing is waiting for four new spars as the current ones are beyond repair. Also the round ends on the wings are also beyond repair. New wing bows will be needed . The Engine was "Pickled" properly but it has not ran for 12 years. It will need to be serviced and check for it's condition. Due to the common use of the engine - it is getting harder to find parts for it
 </p><p>
			Thankfully the person that started the restoration years ago has done a great job of labeling everything.
		<%= image_tag("disassembled.jpg", :class=>"image-size-std  rocket-icon" )%>
        </p>
      </div>
    
		
          <div id="plans"  class="contents order-for  "  style=" padding-top: 15px; margin-top: -15px;">
            <h2>
              The Plan
            </h2>
			<p>
			** This is only an overview, as this plane requires very extensive and meticulous restoration and reassembly.  Needless to say, this list is likely to grow once we get into the project.  At this point in time, here is our overview plan:
		</p>
            <h3>
              The Wing<br>
			  <br>
			  <%= image_tag("spars.jpg", :class=>"image-size-std" )%>
            </h3>
            <ul>
             <li>
               Replace the four Wooden Spars (around $890 each)
              </li><li>
              Replace the wing bows  
              </li><li>
               Reassemble the wing
                </li><li>
              Cover with new fabric
           
			
	  </li>
  </ul>
            <h3>
				The Fuselage
				
            </h3>
			<span class="rocket-icon">
			<%= image_tag("bolts1.jpg", :class=>"image-size-std  " )%><%= image_tag("bolts2.jpg", :class=>"image-size-std " )%></span>
            <ul>
              <li>
           
              Overhaul the cockpit interior
             </li><li>
              Replace the vinyl on the seats with new
             </li><li>
              Confirm condition of all piping & structure ( Ensure no piping is rotting)
             </li><li>
             Replace the Lower lingers
              </li><li>
              Cover it with new fabric
              </li><li>
             Paint and add decals
            </li><li>
             Replace the tires
 	  </li>
   </ul>
			
            <h3>
              The Engine<br><br>
			  <%= image_tag("engine2.jpg", :class=>"image-size-std   " )%>
            </h3>
   	   
     <ul>
		 <li>
            Send it out for recertification
			 
   	  </li>
	 <li>
         Secure spare parts
	  </li>
     </ul>
          </div>
        </div>

        <div class="darker">
          <div class="pullquote content">  <span class="quote open">“</span>It break my heart to see this gem of aviation's history laying in shambles<span class="quote">”</span>        </div>
        </div>



        <div id="author" class="content">
          <h2>About Chris:</h2>
          <div class="author-info">
                          <%= image_tag("chris_harvard_small_med.jpg", :class=>"author-img author-img-size" )%> 

           <span class="highlight">Chris Mailloux</span> is a Skilled Tradesman. He acquired his industrial electrician trade in 2005, specializing in Robot & Computer Programming. He has held positions first as a Manager of Ground Maintenance then as a General Manager of Ground Operations at a International Air-show located in Ontario Canada in 2011 & 2012. Out of his love of working with his hands and attention to detail, Chris has rebuild a number of engines, designed and built custom furniture and designed & built his own computer based Real Time Monitoring Hardware & software.  
           </div>
        </div>

      
    

  <div id="contact" style="padding-top: 50px; margin-top: -50px;">
  </div>
          <div class="contact content" >
            Want more information?  <span class="highlight">email Chris Mailloux</span> 
                         
                        
                        
 <div  class="bootstrap">
                         <%= simple_form_for @message, :html => { :class => 'form-horizontal  contact_text'} , :url => contact_path do |f| %>
                         <table class="table table-striped">

                           <tbody>
                                    <tr>             
                                   <th>
                                         <br>
                 
                                   <%= f.input :name, :label=>"Name:", :placeholder=>"Your Name", :input_html => { :class => "enroll_input span5" } %>
 
         
                                 <%= f.input :email,  :label=>"Email Address:",  :input_html => { :class => "enroll_input span4"}, :wrapper => :append do %>
                                   <%= f.input_field :email,   :placeholder=>"Your Email Address" %><span class="add-on"><i class="icon-envelope"></i></span>
 
   <% end %>

    

                                 <%= f.input :subject,  :label=>'Subject:' , :placeholder=>"Your Question in Short form", :input_html => { :class => "enroll_input span5" } %>
 
                                 <%= f.input :body, :label=>'Message:', :placeholder=>"Your Question", as: :text, :input_html => { :class => "input-xlarge span5", :rows => 10} %>

 
                          <br>
                          
                         
                         </tr>
                         
                         </table>
  
                         <div class="pull-center  ">
                                     <%= f.button :submit, 'Send Message', :class => 'btn btn-warning btn-flat ' %>
                 
        
                                                     </div>
 
                         <% end %>
                        </div>
                        
          </div>
        </div>
      </div> 
	  
	  <%= render 'layouts/footer' %>
	  
	  
</div>

</div>

 

  
 