config/routes.rb
RestoreTheChiefApp::Application.routes.draw do
  resources :site_setups


  resources :posts


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
 
  
 # match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
  devise_scope :user do
      root :to => "home#index" #root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
 devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  resources :users do
    get 'invite', :on => :member
  end
  
  
end

app/models/site_setup.rb
class SiteSetup < ActiveRecord::Base
  attr_accessible :blog_active, :kickstarter, :site_active
end

app/controllers/site_setups_controller.rb
class SiteSetupsController < ApplicationController
  # GET /site_setups
  # GET /site_setups.json
  
  load_and_authorize_resource #:except => [:index, :show ]
  before_filter :authenticate_user! #, :except => [:index, :show ]
  
  def index
    @site_setups = SiteSetup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @site_setups }
    end
  end

  # GET /site_setups/1
  # GET /site_setups/1.json
  def show
    @site_setup = SiteSetup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site_setup }
    end
  end

  # GET /site_setups/new
  # GET /site_setups/new.json
  def new
    @site_setup = SiteSetup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site_setup }
    end
  end

  # GET /site_setups/1/edit
  def edit
    @site_setup = SiteSetup.find(params[:id])
  end

  # POST /site_setups
  # POST /site_setups.json
  def create
    @site_setup = SiteSetup.new(params[:site_setup])

    respond_to do |format|
      if @site_setup.save
        format.html { redirect_to @site_setup, notice: 'Site setup was successfully created.' }
        format.json { render json: @site_setup, status: :created, location: @site_setup }
      else
        format.html { render action: "new" }
        format.json { render json: @site_setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /site_setups/1
  # PUT /site_setups/1.json
  def update
    @site_setup = SiteSetup.find(params[:id])

    respond_to do |format|
      if @site_setup.update_attributes(params[:site_setup])
        format.html { redirect_to @site_setup, notice: 'Site setup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site_setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_setups/1
  # DELETE /site_setups/1.json
  def destroy
    @site_setup = SiteSetup.find(params[:id])
    @site_setup.destroy

    respond_to do |format|
      format.html { redirect_to site_setups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/site_setups_helper.rb
module SiteSetupsHelper
end

app/views/site_setups/_form.html.erb
<%= simple_form_for(@site_setup) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :kickstarter %>
    <%= f.input :site_active %>
    <%= f.input :blog_active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/site_setups/edit.html.erb
<h1>Editing site_setup</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_setup %> |
<%= link_to 'Back', site_setups_path %>

app/views/site_setups/index.html.erb
<h1>Listing site_setups</h1>

<table>
  <tr>
    <th>Kickstarter</th>
    <th>Site active</th>
    <th>Blog active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @site_setups.each do |site_setup| %>
  <tr>
    <td><%= site_setup.kickstarter %></td>
    <td><%= site_setup.site_active %></td>
    <td><%= site_setup.blog_active %></td>
    <td><%= link_to 'Show', site_setup %></td>
    <td><%= link_to 'Edit', edit_site_setup_path(site_setup) %></td>
    <td><%= link_to 'Destroy', site_setup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site setup', new_site_setup_path %>

app/views/site_setups/new.html.erb
<h1>New site_setup</h1>

<%= render 'form' %>

<%= link_to 'Back', site_setups_path %>

app/views/site_setups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kickstarter:</b>
  <%= @site_setup.kickstarter %>
</p>

<p>
  <b>Site active:</b>
  <%= @site_setup.site_active %>
</p>

<p>
  <b>Blog active:</b>
  <%= @site_setup.blog_active %>
</p>


<%= link_to 'Edit', edit_site_setup_path(@site_setup) %> |
<%= link_to 'Back', site_setups_path %>