config/routes.rb
RestoreTheChiefApp::Application.routes.draw do
  resources :site_setups


  resources :posts


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
 
  
 # match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
  devise_scope :user do
      root :to => "home#index" #root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
 devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  resources :users do
    get 'invite', :on => :member
  end
  
  
end

app/views/layouts/_footer.html.erb
<div  id="footer" class="inner"> 
	
	Copyright &copy; <%= DateTime.now.strftime("%Y") %>

   Chris Mailloux
 
	 
 
    </div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 2.3 %>

<div class="bootstrap">

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

</div>

app/views/layouts/_navigation.html.erb
<div class="left-col" >
 
<div class="left-side-bar" >	
			<div class="intrude-less">
			<header id="header" class="inner">
			 <div class="pull-center">	
				<div class="profilepic">	
 <%= link_to image_tag("main_logo.jpg",:class=>'logo_image'  ), root_path, :class=>'logo_image'%>
	
</div>	
</div>
<h1><%= link_to 'Restore the Chief', root_path,  :class=> "sign-up-link" %></h1>
<p class="subtitle">Rescuing A Piece our Heritage</p>
<p class="description">The Restoration of 1343 - a Vintage 1946 Aeronca Chief 11BC.</p>
<nav id="main-nav"><ul class="main">
 
	 <%= render 'layouts/navigation_links' %>
	 <% if user_signed_in? %>
	   <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
	 <% else %>
	   <li><%= link_to 'Login', new_user_session_path %></li>
	 <% end %>
	 <% if user_signed_in? %>
	   <li><%= link_to 'Edit account', edit_user_registration_path %></li>
	 <% else %>
  
	 <% end %>
	 <% if user_signed_in? %>
	   <% if current_user.has_role? :admin %>
	     <li><%= link_to 'Admin', users_path %></li>
  
	     <li><%= link_to 'Site Setup', site_setup_path(@site_setup) %></li>
		   <li><%= link_to 'New Post', new_post_path %></li>
	   <% end %>
	 <% end %>
	 
 
	 
</ul>
</nav>
<nav id="sub-nav">
	<div class="social">
 
		<a class="twitter" href="http://twitter.com/chrismayu" title="Twitter">Twitter</a>

 



	 


	</div>
</nav>


</div>
</div>
 </div>
 

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

  <li><%= link_to 'The Project', root_path + "#project" %></li>

	   <% if @site_setup.blog_active? %>
	       <li><%= link_to 'The Blog', posts_path %></li>
	   <% end %>


   
  <li><%= link_to 'The Plane', root_path + "#plane" %></li>
  
<li>   <%= link_to 'The Challenge', root_path + "#challenge" %></li>

<li><%= link_to 'The Plan', root_path + "#plans" %></li>

<li><%= link_to 'Contact',  new_user_registration_path %></li>
  
 

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Restore The Chief" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Restore The Chief App" %>">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
	
  </head>
  <body>
    <%# application layout styled for Bootstrap 2.3 %>
	<div class="container">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
	  </div>
 <div class="container">
	<div class="mid-col">
	 
				
			
			<div class="mid-col-container">
              <%= render 'layouts/messages' %>
              <%= yield %>
			  
		      </div>
     </div>   
			  
     </div>     
          <footer>
			  
          </footer>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-50862404-1', 'restorethechief.com');
	  ga('send', 'pageview');

	</script>
 
  </body>
</html>